#ifndef CLOX_COMMON_H
#define CLOX_COMMON_H

#include <stdio.h>
#include <stdlib.h>
#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>
#include <string.h>

// trace compiler generated bytecode that passed from compiler to VM
#define DEBUG_COMPILER

// trace VM execution
#define DEBUG_TRACE_EXECUTION

#endif // CLOX_COMMON_H
